"""baseline schema

Revision ID: f652273fd930
Revises: 
Create Date: 2026-07-31 22:09:20.198865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f652273fd930'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('osm_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bbox_west', sa.Float(), nullable=False),
    sa.Column('bbox_south', sa.Float(), nullable=False),
    sa.Column('bbox_east', sa.Float(), nullable=False),
    sa.Column('bbox_north', sa.Float(), nullable=False),
    sa.Column('force_buildings', sa.Boolean(), nullable=False),
    sa.Column('response', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_osm_cache_key', 'osm_cache', ['bbox_west', 'bbox_south', 'bbox_east', 'bbox_north', 'force_buildings'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('reset_token', sa.String(length=255), nullable=True),
    sa.Column('reset_token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('design_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('merch_type', sa.String(length=50), nullable=False),
    sa.Column('bbox_west', sa.Float(), nullable=False),
    sa.Column('bbox_south', sa.Float(), nullable=False),
    sa.Column('bbox_east', sa.Float(), nullable=False),
    sa.Column('bbox_north', sa.Float(), nullable=False),
    sa.Column('style', sa.String(length=50), server_default='osm_default', nullable=False),
    sa.Column('coaster_shape', sa.String(length=50), nullable=True),
    sa.Column('palette_overrides', sa.JSON(), nullable=True),
    sa.Column('include_labels', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('include_buildings', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('thumbnail_data_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_design_projects_user_id'), 'design_projects', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_design_projects_user_id'), table_name='design_projects')
    op.drop_table('design_projects')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_osm_cache_key', table_name='osm_cache')
    op.drop_table('osm_cache')
    # ### end Alembic commands ###
